### ISSUE TITLE
release

### ISSUE THREAD

**Issue by wong-fi-hung** [ONYXcore/onyx#1]
add release for arm64 please.....

**Comment by ONYXcore** [comment]
Hello, we will try to provide you with this quickly.

**Comment by wong-fi-hung** [comment]
> Hello, we will try to provide you with this quickly.

thank you :)

**Comment by ONYXcore** [comment]
> > Hello, we will try to provide you with this quickly.
> 
> thank you :)

Can you please try this and tell me if it works:
https://github.com/ONYXcore/onyx/releases/download/v1.0.2/onyx-arm64.zip

**Comment by wong-fi-hung** [comment]
this works :D 
but the segwit fail...
look like this:

udin@localhost:~$ onyx-cli getblockchaininfo
{
  "chain": "main",
  "blocks": 144266,
  "headers": 144266,
  "bestblockhash": "000002dd44741bb277cc7e5392f395b602f8171d919c4e54044fe28ff27d084c",
  "difficulty": 0.000767089252645899,                                            "mediantime": 1662181047,
  "verificationprogress": 1,
  "initialblockdownload": false,
  "chainwork": "000000000000000000000000000000000000000000000000000000603bebb329",
  "size_on_disk": 88837965,
  "pruned": false,
  "softforks": [
    {
      "id": "bip34",
      "version": 2,
      "reject": {
        "status": true
      }
    },
    {
      "id": "bip66",
      "version": 3,
      "reject": {
        "status": true
      }
    },
    {
      "id": "bip65",
      "version": 4,
      "reject": {
        "status": true
      }
    }
  ],
  "bip9_softforks": {
    "csv": {
      "status": "failed",
      "startTime": 1556668800,
      "timeout": 1588291200,
      "since": 12240
    },
    "segwit": {
      "status": "failed",
      "startTime": 1556668800,
      "timeout": 1588291200,
      "since": 12240
    }
  },
  "warnings": ""
}

**Comment by wong-fi-hung** [comment]
another log file:
1. https://github.com/wong-fi-hung/cli_wallet_debug_log_file/blob/master/debug1.log
2. https://github.com/wong-fi-hung/cli_wallet_debug_log_file/blob/master/debug2.log
